name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: what
    attributes:
      label: What do you want?
      description: Describe the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: What problem does this solve or what use case does it enable?
    validations:
      required: false
